services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    container_name: master-api-container
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      TZ: Asia/Jakarta
    restart: always
    command: npm run start:dev
    volumes:
      - master-api-volume:/vol/app
      - .:/vol/app
    networks:
      - shared-networks

volumes:
  master-api-volume:
    name: master-api-volume
    driver: local

networks:
  shared-networks:
    name: shared-networks
    driver: bridge
    external: true
